site_name: PyTorch-LifeStream
nav:
    - Welcome: index.md
    - 'User Guide':
        - 'Data Preparation': 'data_preparation.md'
        - 'Training Methods': 'methods.md'
        - seq_encoder: 'seq_encoder.md'
        - trx_encoder: 'trx_encoder.md'
theme: readthedocs
