site_name: PyTorch-LifeStream
nav:
    - Welcome: index.md
    - 'User Guide':
        - 'Data Preparation': 'data_preparation.md'
        - 'Training Methods': 'methods.md'
        - 'ptls.nn':
            - 'trx_encoder': 'nn/trx_encoder.md'
            - 'seq_encoder': 'nn/seq_encoder.md'
            - 'head': 'nn/head.md'
            - 'pb layers': 'nn/pb.md'
theme: readthedocs
